/* 
 * File:   mcal_interrupt_gen_cfg.h
 * Author: Eng A_Esam
 *
 * Created on May 29, 2023, 10:21 PM
 */

#ifndef MCAL_INTERRUPT_GEN_CFG_H
#define	MCAL_INTERRUPT_GEN_CFG_H

#define INTERRUPT_FEATURE_ENABLE  1
#define INTERRUPT_FEATURE_DISABLE  0

#define INTERUPT_PRIORITY_LEVELS_ENABLE               INTERRUPT_FEATURE_DISABLE

#define EXTERNAL_INTERRUPT_INTX_FEATURE_ENABLE        INTERRUPT_FEATURE_ENABLE
#define EXTERNAL_INTERRUPT_onChange_FEATURE_ENABLE    INTERRUPT_FEATURE_ENABLE

#define ADC_INTERRUPT_FEATURE_ENABLE     INTERRUPT_FEATURE_ENABLE

#define TIMER0_INTERRUPT_FEATURE_ENABLE  INTERRUPT_FEATURE_ENABLE
#define TIMER1_INTERRUPT_FEATURE_ENABLE  INTERRUPT_FEATURE_ENABLE
#define TIMER2_INTERRUPT_FEATURE_ENABLE  INTERRUPT_FEATURE_ENABLE
#define TIMER3_INTERRUPT_FEATURE_ENABLE  INTERRUPT_FEATURE_ENABLE

#define CCP1_INTERRUPT_FEATURE_ENABLE  INTERRUPT_FEATURE_ENABLE
#define CCP2_INTERRUPT_FEATURE_ENABLE  INTERRUPT_FEATURE_ENABLE

#define EUSART_TX_INTERRUPT_FEATURE_ENABLE  INTERRUPT_FEATURE_ENABLE
#define EUSART_RX_INTERRUPT_FEATURE_ENABLE  INTERRUPT_FEATURE_ENABLE

#define MSSP_SPI_INTERRUPT_FEATURE_ENABLE  INTERRUPT_FEATURE_ENABLE

#define MSSP_I2C_INTERRUPT_FEATURE_ENABLE  INTERRUPT_FEATURE_ENABLE

#endif	/* MCAL_INTERRUPT_GEN_CFG_H */

